#!/bin/bash

if [ $# != 1 ]
then
  echo "usage: package-cfn <bucket-name>"
  exit 1
fi

aws cloudformation package --template-file cloud-formation-template.yaml --s3-bucket $1 --output-template-file cloud-formation-deploy.yaml